"""add_content_fields_to_collections

Revision ID: 92ee5cc45a47
Revises: 45913054e787
Create Date: 2026-01-22 16:49:36.267330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ee5cc45a47'
down_revision: Union[str, None] = '45913054e787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('content_id', sa.UUID(), nullable=True))
    op.add_column('collections', sa.Column('content_data', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_collections_content_id'), 'collections', ['content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_content_id'), table_name='collections')
    op.drop_column('collections', 'content_data')
    op.drop_column('collections', 'content_id')
    # ### end Alembic commands ###
