"""add image_urls to records

Revision ID: 035842bc2765
Revises: a53fcce6abea
Create Date: 2026-01-30 16:42:48.852646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035842bc2765'
down_revision: Union[str, None] = 'a53fcce6abea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('image_urls', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'image_urls')
    # ### end Alembic commands ###
